criando_blog_com_ruby_on_rails/blog/config/routes.rb
Rails.application.routes.draw do
  resources :livros
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "livros#index"
end

criando_blog_com_ruby_on_rails/blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

criando_blog_com_ruby_on_rails/blog/app/models/livro.rb
class Livro < ApplicationRecord
end

criando_blog_com_ruby_on_rails/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

criando_blog_com_ruby_on_rails/blog/app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  before_action :set_livro, only: %i[ show edit update destroy ]

  # GET /livros or /livros.json
  def index
    @livros = Livro.all
  end

  # GET /livros/1 or /livros/1.json
  def show
  end

  # GET /livros/new
  def new
    @livro = Livro.new
  end

  # GET /livros/1/edit
  def edit
  end

  # POST /livros or /livros.json
  def create
    @livro = Livro.new(livro_params)

    respond_to do |format|
      if @livro.save
        format.html { redirect_to livro_url(@livro), notice: "Livro was successfully created." }
        format.json { render :show, status: :created, location: @livro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /livros/1 or /livros/1.json
  def update
    respond_to do |format|
      if @livro.update(livro_params)
        format.html { redirect_to livro_url(@livro), notice: "Livro was successfully updated." }
        format.json { render :show, status: :ok, location: @livro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /livros/1 or /livros/1.json
  def destroy
    @livro.destroy

    respond_to do |format|
      format.html { redirect_to livros_url, notice: "Livro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_livro
      @livro = Livro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def livro_params
      params.require(:livro).permit(:titulo, :autor, :nota, :descricao)
    end
end

criando_blog_com_ruby_on_rails/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

criando_blog_com_ruby_on_rails/blog/app/helpers/livros_helper.rb
module LivrosHelper
end

criando_blog_com_ruby_on_rails/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

criando_blog_com_ruby_on_rails/blog/app/views/livros/_form.html.erb
<%= form_with(model: livro) do |form| %>
  <% if livro.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(livro.errors.count, "error") %> prohibited this livro from being saved:</h2>

      <ul>
        <% livro.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titulo, style: "display: block" %>
    <%= form.text_field :titulo %>
  </div>

  <div>
    <%= form.label :autor, style: "display: block" %>
    <%= form.text_field :autor %>
  </div>

  <div>
    <%= form.label :nota, style: "display: block" %>
    <%= form.number_field :nota %>
  </div>

  <div>
    <%= form.label :descricao, style: "display: block" %>
    <%= form.text_field :descricao %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

criando_blog_com_ruby_on_rails/blog/app/views/livros/_livro.html.erb
<div id="<%= dom_id livro %>">
  <p>
    <strong>Titulo:</strong>
    <%= livro.titulo %>
  </p>

  <p>
    <strong>Autor:</strong>
    <%= livro.autor %>
  </p>

  <p>
    <strong>Nota:</strong>
    <%= livro.nota %>
  </p>

  <p>
    <strong>Descricao:</strong>
    <%= livro.descricao %>
  </p>

</div>

criando_blog_com_ruby_on_rails/blog/app/views/livros/edit.html.erb
<h1>Editing livro</h1>

<%= render "form", livro: @livro %>

<br>

<div>
  <%= link_to "Show this livro", @livro %> |
  <%= link_to "Back to livros", livros_path %>
</div>

criando_blog_com_ruby_on_rails/blog/app/views/livros/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Livros</h1>

<div id="livros">
  <% @livros.each do |livro| %>
    <%= render livro %>
    <p>
      <%= link_to "Show this livro", livro %>
    </p>
  <% end %>
</div>

<%= link_to "New livro", new_livro_path %>

criando_blog_com_ruby_on_rails/blog/app/views/livros/new.html.erb
<h1>New livro</h1>

<%= render "form", livro: @livro %>

<br>

<div>
  <%= link_to "Back to livros", livros_path %>
</div>

criando_blog_com_ruby_on_rails/blog/app/views/livros/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @livro %>

<div>
  <%= link_to "Edit this livro", edit_livro_path(@livro) %> |
  <%= link_to "Back to livros", livros_path %>

  <%= button_to "Destroy this livro", @livro, method: :delete %>
</div>